# Generated by Django 5.2.8 on 2025-11-08 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                ("cep", models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                (
                    "patrimony_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accessories", models.TextField(blank=True)),
                ("defect", models.TextField()),
                ("observation", models.TextField(blank=True)),
                ("entry_date", models.DateTimeField(auto_now_add=True)),
                ("repair_details", models.TextField(blank=True)),
                (
                    "repair_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("resolution", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Aberto", "Aberto"),
                            ("Em andamento", "Em andamento"),
                            ("Aguardando peça", "Aguardando peça"),
                            ("Finalizado", "Finalizado"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Aberto",
                        max_length=20,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_orders",
                        to="service_order.client",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_orders",
                        to="service_order.device",
                    ),
                ),
            ],
        ),
    ]
